version: "3"
services:
  client:
    build: .
    image: spa_vue_js_hello-world_composition-api:basic-authn-with-api
    container_name: spa_vue_js_hello-world_composition-api_basic-authn-with-api
    ports:
      - 4040:4040
    env_file:
      - .env
